import pandas as pd
import oracledb

from typing import Optional

def replace_env_variables(s: str) -> str: ...
def generate_select(table_name: str) -> str:...
def get_class_of_series(series: pd.Series) -> str:...
def extract_class_name(text: str) -> Optional[str]:...
def get_data_type_from_values(values: pd.Series) -> Optional[str]:...
def get_classes_from_dtypes(dtypes: pd.Series) -> dict:...
def none_for_nan(df: pd.DataFrame,num2str: bool = False) -> pd.DataFrame:...
def date2datetime(df: pd.DataFrame) -> pd.DataFrame:...
def datetime2date(df: pd.DataFrame) -> pd.DataFrame:...
def get_table(table_name: str, crsr: oracledb.Cursor, clean_output: bool =True) -> pd.DataFrame:...
def exists_table(table_name: str ,crsr: oracledb.Cursor) -> bool:... 