import pandas as pd

from typing import Optional

def get_class_of_series(series: pd.Series) -> str:...
def extract_class_name(text: str) -> Optional[str]:...
def get_data_type_from_values(values: pd.Series) -> Optional[str]:...
def get_classes_from_dtypes(dtypes: pd.Series) -> dict:...
def none_for_nan(df: pd.DataFrame,num2str: bool = False) -> pd.DataFrame:...
def date2datetime(df: pd.DataFrame) -> pd.DataFrame:...
def datetime2date(df: pd.DataFrame) -> pd.DataFrame:...
